version: "3"
volumes:
  node_modules:
services:
  prototype:
    container_name: "zizityp"
    volumes:
      - .:/frontend
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/frontend'
      - 'node_modules:/frontend/node_modules'
    ports:
      - 8080:8080